{
 "title": "Bookoo Live Shot",
 "tags": [
  "bookoo",
  "espresso"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "pressure_entity",
    "label": "Pressure entity_id",
    "query": "bookoo_espresso_monitor_pressure"
   },
   { "name": "weight_entity", "label": "Weight entity_id", "query": "bookoo_smart_scale_mini_weight" },
   { "name": "flow_entity", "label": "Flow entity_id", "query": "bookoo_smart_scale_mini_flow" },
   { "name": "timer_entity", "label": "Timer entity_id", "query": "bookoo_smart_scale_mini_timer" }
  ]
 },
 "panels": [
  {
   "title": "Current shot",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bar",
     "query": "SELECT mean(\"value\") FROM \"bar\" WHERE (\"entity_id\" = '${pressure_entity}') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Flow",
     "query": "SELECT mean(\"value\") FROM \"g/s\" WHERE (\"entity_id\" = '${flow_entity}') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "Weight",
     "query": "SELECT mean(\"value\") FROM \"g\" WHERE (\"entity_id\" = '${weight_entity}') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"bar\" WHERE (\"entity_id\" = '${pressure_entity}') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Yield",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "g" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"g\" WHERE (\"entity_id\" = '${weight_entity}') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Timer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"s\" WHERE (\"entity_id\" = '${timer_entity}') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Flow",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "gps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"g/s\" WHERE (\"entity_id\" = '${flow_entity}') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Recent Shot Lab summaries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT last(\"duration_s\") AS \"duration\", last(\"final_weight_g\") AS \"yield\", last(\"max_pressure_bar\") AS \"max pressure\", last(\"avg_flow_g_s\") AS \"avg flow\" FROM \"bookoo_shots\" WHERE $timeFilter GROUP BY \"shot_id\""
    }
   ]
  }
 ]
}